<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416222052 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE level1 (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, level2_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7F844A58C34057D ON level1 (level2_id)');
        $this->addSql('CREATE TABLE level2 (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, level3_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9EF1151F34886218 ON level2 (level3_id)');
        $this->addSql('CREATE TABLE level3 (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, level4_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E9F62589A95F5AA1 ON level3 (level4_id)');
        $this->addSql('CREATE TABLE level4 (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE level1 ADD CONSTRAINT FK_7F844A58C34057D FOREIGN KEY (level2_id) REFERENCES level2 (id)');
        $this->addSql('ALTER TABLE level2 ADD CONSTRAINT FK_9EF1151F34886218 FOREIGN KEY (level3_id) REFERENCES level3 (id)');
        $this->addSql('ALTER TABLE level3 ADD CONSTRAINT FK_E9F62589A95F5AA1 FOREIGN KEY (level4_id) REFERENCES level4 (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE level1 DROP CONSTRAINT FK_7F844A58C34057D');
        $this->addSql('ALTER TABLE level2 DROP CONSTRAINT FK_9EF1151F34886218');
        $this->addSql('ALTER TABLE level3 DROP CONSTRAINT FK_E9F62589A95F5AA1');
        $this->addSql('DROP TABLE level1');
        $this->addSql('DROP TABLE level2');
        $this->addSql('DROP TABLE level3');
        $this->addSql('DROP TABLE level4');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
